{
 "title": "AlephZero Metrics - new",
 "description": "Grafana dashboard for substrate template metrics. Instructions on use: https://substrate.dev/docs/en/tutorials/visualize-node-metrics/",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "template",
  "polkadot",
  "kusama"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Importing -> Imported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "substrate_aleph_Imported" }
   ]
  },
  {
   "title": "Imported -> Ordering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "substrate_aleph_Ordering" }
   ]
  },
  {
   "title": "Ordering -> Ordered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "substrate_aleph_Ordered" }
   ]
  },
  {
   "title": "Ordered -> Aggregating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "substrate_aleph_Aggregating" }
   ]
  },
  {
   "title": "Aggregating -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "substrate_aleph_Finalized" }
   ]
  },
  {
   "title": "Importing -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "substrate_aleph_Imported + substrate_aleph_Ordering + substrate_aleph_Ordered + substrate_aleph_Aggregating + substrate_aleph_Finalized"
    }
   ]
  },
  { "title": "Other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "txps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions / (substrate_aleph_Imported + substrate_aleph_Ordering + substrate_aleph_Ordered + substrate_aleph_Aggregating + substrate_aleph_Finalized)"
    }
   ]
  },
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "Block Total Tx",
   "type": "stat",
   "description": "Total transactions in best block",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Size (bytes)" }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Proposer Block Construction Time",
   "type": "graph",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Time (s)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(substrate_proposer_block_constructed_bucket[5m])) by (le))",
     "legendFormat": "90th quantile for block construction time (s)"
    }
   ]
  }
 ]
}