FROM nixos/nix:2.6.0

COPY docker/nix-build.sh /node/
RUN chmod +x /node/nix-build.sh
COPY shell.nix /node/
WORKDIR /node
RUN nix-shell --pure shell.nix && \
    nix-env -i patchelf

WORKDIR /node/build
ENTRYPOINT ["/node/nix-build.sh"]
CMD []