FROM nixos/nix:2.6.0

COPY docker/nix-build.sh /
COPY . /node/
WORKDIR /node
RUN nix-env -i patchelf && \
    nix-collect-garbage -d
RUN nix-build ./default.nix && \
    rm -rf /node/ && \
    mv /nix-build.sh /node/ && \
    chmod +x /node/nix-build.sh

WORKDIR /node/build
ENTRYPOINT ["/node/nix-build.sh"]
CMD []