FROM nixos/nix:2.6.0

COPY docker/nix-build.sh /node/
COPY . /node/build
RUN nix-env -i patchelf && \
    nix-collect-garbage -d && \
    chmod +x /node/nix-build.sh

WORKDIR /node/build
RUN nix-build ./default.nix && \
    rm -rf /node/build

WORKDIR /node/build
ENTRYPOINT ["/node/nix-build.sh"]
CMD []